moved options documentation to separate page
mdolab/pyhyp pull request #24
Opened 2020-09-07 20:45 UTC by sseraj

## Purpose
The options table is currently buried in the Plot3d tutorial. I moved the table to a separate page on the top level to increase visibility. This is consistent with the ADflow and IDWarp docs. I also added the text wrapping fix for the table.

## Type of change
- Documentation update

2020-09-07 22:46 UTC, nwu63 commented
Currently, all the examples show up on a single page, despite CGNS and Plot3D being listed as separate pages on the side bar. Would you mind splitting it up into separate files so that they will render as separate pages? I think that's preferable to having a top-level heading called `Example Usage` or something and putting everything under that.

2020-09-07 23:18 UTC, nwu63 submitted a review, later dismissed

2020-09-08 21:28 UTC, eirikurj requested changes
Good update.
@sseraj since you are updating these files, can you fix the quotation/backticks issues?
In many places there is a mix of quotes i.e., `` ` `` and `'` resulting in many words not rendered.

2020-09-08 21:28 UTC, eirikurj commented on doc/conf.py
> +        '_static/theme_overrides.css',  # override wide tables in RTD theme
Please change to double quotes to make the file consistent

2020-09-08 21:28 UTC, eirikurj commented on doc/options.rst
> +`fileType`            `char`   Type of the input file. Use either 'Plot3d' or 'CGNS'.
This is one example of incorrect quotes. Please change to backticks.

2020-09-08 22:54 UTC, sseraj commented
I think this addresses the quote/backtick issues.

2020-09-08 23:09 UTC, nwu63 commented
So technically all the single backticks should be double backticks, since we want the fixed width formatting for those. Would you mind doing that?

2020-09-09 02:36 UTC, sseraj commented
The few extra characters wreaked havoc on the table formatting so I had to change the spacing. I split each sentence into its own line like we try to do with the docs.

2020-09-09 02:47 UTC, sseraj commented
Travis is failing on `py3-centos7-impi` because: `Error: Product support for your (Comp-FL) license has expired.`

2020-09-09 03:13 UTC, nwu63 commented
Thanks for that, table looks much more legible now. Yeah I'm not sure why the license expired, I thought we build that nightly. Anyways, I'm fine merging this in since it only touches the docs.

2020-09-09 03:13 UTC, nwu63 approved these changes

2020-09-09 19:05 UTC, eirikurj approved these changes
I am approving for now, but we need to adjust many of the other pages in this repo as well as its mixed and single backticks all over the place.
We should adjust how we present the options table for other repos also.

2020-09-09 19:05 UTC, merged

2020-09-09 19:08 UTC, nwu63 commented
Yeah, now that we are rolling out the CSS "hack" for tables, I am much more inclined to throw that in a repo and upload it to pyPI. Will comment on the appropriate issue and elicit help.