Format update and improved exception - output handling
mdolab/pyhyp pull request #31
Opened 2020-10-30 14:02 UTC by marcomangano

## Purpose
I re-formatted the code, as per [this issue](https://github.com/mdolab/private-docs/issues/191).
I also took the opportunity to fix a couple of bad code lines.
Now `generateOutputName()` requires the output type, as an input, i.e. I removed `outputType=None`
I recommend to fix the other bad practices in the code in another PR soon.

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (non-backwards-compatible fix or feature)
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [x] Maintenance update
- [ ] Other (please describe)

## Checklist
_Put an `x` in the boxes that apply._

- [x] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [ ] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

2020-10-30 14:12 UTC, nwu63 requested changes
Changes look good, but it seems that you missed 2 files for `black` and a few linting errors remain.

2020-10-30 16:25 UTC, nwu63 requested changes
Flake8 is still failing. I typically run `flake8` locally to make sure everything is okay, might be faster than using Travis. Also a few comments can be cleaned up

2020-10-30 16:25 UTC, nwu63 commented on pyhyp/MExt.py
> +            except ImportError:  # What kind of exception is this?
Can remove the comment

2020-10-30 16:25 UTC, nwu63 commented on pyhyp/MExt.py
>              # on win32, the DLL must be unloaded forcefully in order to delete it.
Can remove these comments too

2020-10-30 16:35 UTC, marcomangano commented
Thanks, will fix that soon

2020-10-30 16:46 UTC, nwu63 submitted a review, later dismissed

2020-10-31 08:55 UTC, marcomangano commented
This is good to go for me.

2020-10-31 14:57 UTC, nwu63 submitted a review, later dismissed

2020-11-03 17:57 UTC, sseraj reviewed
Looks good! Some minor comments below

2020-11-03 17:57 UTC, sseraj commented on doc/conf.py
> +from sphinx_mdolab_theme.config import *  # noqa: F403
I am inclined to remove the noqas because this file should now be ignored after changes to .github.

2020-11-03 17:57 UTC, sseraj commented on pyhyp/__init__.py
> +__all__ = ["pyHyp", "pyHypMulti"]
I think the init files are also ignored so I don't think we need this.

2020-11-03 18:01 UTC, marcomangano commented
Agreed, I have removed those `flake8 .` fixes

2020-11-03 18:03 UTC, sseraj commented on doc/conf.py
> +extensions.extend(["numpydoc"])  # noqa: F405
Just one left

2020-11-03 18:19 UTC, sseraj approved these changes

2020-11-03 19:06 UTC, nwu63 approved these changes

2020-11-03 19:18 UTC, merged